spring:
  profiles:
    active: local # 기본 실행 환경 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true