spring:
  datasource:
    # RDS 엔드포인트 또는 EC2 탄력적 IP 주소
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver