spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234 # 본인 로컬 DB 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver